name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
      - name: Install cargo
        uses: actions-rs/install@v0.1.2
        with:
          crate: cargo-audit
          version: latest
      - name: Install selene
        run: cargo install selene
      - name: Lint check
        run: selene ./
