name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
      - name: Install selene
        uses: actions-rs/install@v0.1
        with:
          crate: selene
          version: latest
      - name: Lint check
        run: selene ./
