name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2
      - name: Install selene
        run: |
          wget -q https://github.com/Kampfkarren/selene/releases/download/0.9.2/selene-0.9.2-linux.zip -o temp.zip
          unzip temp.zip
      - name: Lint check
        run: ./selene ./
